### ISSUE TITLE
Support for global variables (with example)

### ISSUE THREAD

**Issue by StayFrozty** [YAL-GameMaker/tiny-expression-runtime#2]
Hiya! So I wanted to add support for getting and setting global variables, and it actually wound up being even simpler than I originally expected. The only change required is to the _txr_thread_resume_ script. Simply replace the txr_action.ident and txr_action.set_ident case statement values with the following:

```	       
 case txr_action.ident:
	if (variable_instance_exists(id, q[2]))
	{
		var v = variable_instance_get(id, q[2]);
	}
	else
	{
		var v = variable_global_get(q[2]);	
	}
	ds_stack_push(stack, v);
	break;
case txr_action.set_ident:
	if (!variable_global_exists(q[2]))
	{
		variable_instance_set(id, q[2], ds_stack_pop(stack));
	}
	else
	{
		variable_global_set(q[2], ds_stack_pop(stack));
	}
	break;
```

I've yet to find a situation in which this doesn't work, and it ensures you don't have local variables that are set with the same identifiers as global variables. A neat little fix.

**Comment by YellowAfterlife** [comment]
I would generally recommend handling `txr_node.field` to emit a different action if the "object" is a `global` identifier, or simply emitting a different action based on the name of `ident`
